volumes:
  common-oracle-db:
    name: 'common-oracle-db'

services:

  oracle:
    image: gvenzl/oracle-xe:${ORACLE_IMAGE_TAG}
    tty: true
    env_file:
      - .envs/oracle.env
    volumes:
      - common-oracle-db:${ORACLE_VOLUME_CONTAINER_DIR}
    networks:
     tech-care:
        aliases:
          - common-oracle
